name = "nexus-do"
main = "nexus_do.mjs"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "aquan.lufei.uk", zone_id = "824bdc2b31476c82c066e28ca1fa5a68" }
]

[[durable_objects.bindings]]
name = "SHENSHU"
class_name = "ShenshuCore"


[[kv_namespaces]]
binding = "SOUL_KV"
id = "2978edea205e462d97cd3613f4745fbf"

[ai]
binding = "AI"
